Repository zaphiro-technologies/github-workflows, pull requests merged in 2023-11, with the labels that each got.

#63 docker workflow: add git and build information as build arguments
  .github/workflows/docker.yaml
  RELEASE_NOTES.md
Labels: feature

#68 Lower annotation pollution on PRs
  .github/config/wordlist.txt
  .github/workflows/golang.yaml
  RELEASE_NOTES.md
Labels: ci

#65 markdown workflow: support correctly `.prettierignore`
  .github/config/.prettierignore
  .github/config/wordlist.txt
  .github/workflows/markdown.yaml
  RELEASE_NOTES.md
  __tests__/test.md
Labels: bug

#64 golang: add docker login on test and benchmark workflows
  .github/workflows/golang.yaml
  README.MD
  RELEASE_NOTES.md
Labels: feature
