Repository zaphiro-technologies/github-workflows, pull requests merged in 2024-05, with the labels that each got.

#112 markdown workflow: Use quiet mode for link checker
  .github/workflows/markdown.yaml
  RELEASE_NOTES.md
Labels: feature

#115 Add the deployment workflow
  .github/workflows/deployment.yaml
  README.MD
  RELEASE_NOTES.md
Labels: feature

#116 license, docker, golang, release notes workflows: support SBOM generation, license compatibility check and vulnerability check
  .github/workflows/docker.yaml
  .github/workflows/golang.yaml
  .github/workflows/license.yaml
  .github/workflows/release-notes.yaml
  README.MD
  RELEASE_NOTES.md
Labels: feature

#119 Move sonarcloud checks to test job
  .github/workflows/golang.yaml
  RELEASE_NOTES.md
Labels: ci

#120 Fix deployment workflow on PRs
  .github/workflows/deployment.yaml
  RELEASE_NOTES.md
Labels: bug

#121 docker wf: support concurrent image builds
  .github/workflows/docker.yaml
  RELEASE_NOTES.md
Labels: feature
